/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as FaqIndexRouteImport } from './routes/faq.index'
import { Route as FaqGeneralRouteImport } from './routes/faq.general'
import { Route as FaqSecurityRouteImport } from './routes/faq.security'
import { Route as FaqTroubleshootingRouteImport } from './routes/faq.troubleshooting'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqIndexRoute = FaqIndexRouteImport.update({
  id: '/faq/',
  path: '/faq/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqGeneralRoute = FaqGeneralRouteImport.update({
  id: '/faq/general',
  path: '/faq/general',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqSecurityRoute = FaqSecurityRouteImport.update({
  id: '/faq/security',
  path: '/faq/security',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqTroubleshootingRoute = FaqTroubleshootingRouteImport.update({
  id: '/faq/troubleshooting',
  path: '/faq/troubleshooting',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-to-play': typeof HowToPlayRoute
  '/updates': typeof UpdatesRoute
  '/faq/general': typeof FaqGeneralRoute
  '/faq/security': typeof FaqSecurityRoute
  '/faq/troubleshooting': typeof FaqTroubleshootingRoute
  '/faq/': typeof FaqIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-to-play': typeof HowToPlayRoute
  '/updates': typeof UpdatesRoute
  '/faq/general': typeof FaqGeneralRoute
  '/faq/security': typeof FaqSecurityRoute
  '/faq/troubleshooting': typeof FaqTroubleshootingRoute
  '/faq': typeof FaqIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how-to-play': typeof HowToPlayRoute
  '/updates': typeof UpdatesRoute
  '/faq/general': typeof FaqGeneralRoute
  '/faq/security': typeof FaqSecurityRoute
  '/faq/troubleshooting': typeof FaqTroubleshootingRoute
  '/faq/': typeof FaqIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how-to-play'
    | '/updates'
    | '/faq/general'
    | '/faq/security'
    | '/faq/troubleshooting'
    | '/faq/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-to-play'
    | '/updates'
    | '/faq/general'
    | '/faq/security'
    | '/faq/troubleshooting'
    | '/faq'
  id:
    | '__root__'
    | '/'
    | '/how-to-play'
    | '/updates'
    | '/faq/general'
    | '/faq/security'
    | '/faq/troubleshooting'
    | '/faq/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowToPlayRoute: typeof HowToPlayRoute
  UpdatesRoute: typeof UpdatesRoute
  FaqGeneralRoute: typeof FaqGeneralRoute
  FaqSecurityRoute: typeof FaqSecurityRoute
  FaqTroubleshootingRoute: typeof FaqTroubleshootingRoute
  FaqIndexRoute: typeof FaqIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/': {
      id: '/faq/'
      path: '/faq'
      fullPath: '/faq/'
      preLoaderRoute: typeof FaqIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/general': {
      id: '/faq/general'
      path: '/faq/general'
      fullPath: '/faq/general'
      preLoaderRoute: typeof FaqGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/security': {
      id: '/faq/security'
      path: '/faq/security'
      fullPath: '/faq/security'
      preLoaderRoute: typeof FaqSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/troubleshooting': {
      id: '/faq/troubleshooting'
      path: '/faq/troubleshooting'
      fullPath: '/faq/troubleshooting'
      preLoaderRoute: typeof FaqTroubleshootingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowToPlayRoute: HowToPlayRoute,
  UpdatesRoute: UpdatesRoute,
  FaqGeneralRoute: FaqGeneralRoute,
  FaqSecurityRoute: FaqSecurityRoute,
  FaqTroubleshootingRoute: FaqTroubleshootingRoute,
  FaqIndexRoute: FaqIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
