pragma circom 2.0.4;

// Building blocks of the fixed GKR verifier. The per-circuit verifier template itself is
// generated by rust/src/circom_codegen.rs (`gkr_verifier_template`), because the circuit
// wiring must be compile-time constants of the verifier: upstream's generic
// VerifyGKR(meta) took challenges, points, the output polynomial and the input
// polynomial as free prover inputs, hard-coded the initial claim to 0 at a
// prover-chosen point, and never checked a layer's sumcheck against the circuit wiring.

include "./poly/univariate.circom";
include "./poly/multivariate.circom";
include "./sumcheck/sumcheckVerify.circom";
include "./transcript.circom";
