// @generated by `mania-gkr-sui export-move`; do not edit.
#[test_only]
module mania_gkr::generated_tests;

use mania_gkr::fixtures;
use mania_gkr::test_util;

#[test]
fun chart_demo() {
    test_util::check_chart(&fixtures::case_demo_a(), fixtures::chart_bytes_demo(), fixtures::chart_proof_demo());
}

#[test]
fun verify_demo_a() {
    test_util::check_verify(&fixtures::case_demo_a(), fixtures::trace_t_demo_a(), fixtures::trace_la_demo_a());
}

#[test]
fun submit_demo_a() {
    test_util::check_submit(&fixtures::case_demo_a(), fixtures::chart_bytes_demo(), fixtures::chart_proof_demo(), fixtures::events_demo_a(), fixtures::trace_t_demo_a(), fixtures::trace_la_demo_a());
}

#[test]
fun upload_demo_a() {
    test_util::check_upload(&fixtures::case_demo_a(), fixtures::events_demo_a());
}

#[test, expected_failure]
fun reject_demo_a_adv_commitment() {
    test_util::check_verify_proof(&fixtures::case_demo_a(), fixtures::tampered_demo_a_adv_commitment(), fixtures::trace_t_demo_a(), fixtures::trace_la_demo_a());
}

#[test, expected_failure]
fun reject_demo_a_gkr_layer1() {
    test_util::check_verify_proof(&fixtures::case_demo_a(), fixtures::tampered_demo_a_gkr_layer1(), fixtures::trace_t_demo_a(), fixtures::trace_la_demo_a());
}

#[test, expected_failure]
fun reject_demo_a_gkr_round() {
    test_util::check_verify_proof(&fixtures::case_demo_a(), fixtures::tampered_demo_a_gkr_round(), fixtures::trace_t_demo_a(), fixtures::trace_la_demo_a());
}

#[test, expected_failure]
fun reject_demo_a_gkr_children() {
    test_util::check_verify_proof(&fixtures::case_demo_a(), fixtures::tampered_demo_a_gkr_children(), fixtures::trace_t_demo_a(), fixtures::trace_la_demo_a());
}

#[test, expected_failure]
fun reject_demo_a_row_round() {
    test_util::check_verify_proof(&fixtures::case_demo_a(), fixtures::tampered_demo_a_row_round(), fixtures::trace_t_demo_a(), fixtures::trace_la_demo_a());
}

#[test, expected_failure]
fun reject_demo_a_claim_first() {
    test_util::check_verify_proof(&fixtures::case_demo_a(), fixtures::tampered_demo_a_claim_first(), fixtures::trace_t_demo_a(), fixtures::trace_la_demo_a());
}

#[test, expected_failure]
fun reject_demo_a_claim_last() {
    test_util::check_verify_proof(&fixtures::case_demo_a(), fixtures::tampered_demo_a_claim_last(), fixtures::trace_t_demo_a(), fixtures::trace_la_demo_a());
}

#[test, expected_failure]
fun reject_demo_a_red_round() {
    test_util::check_verify_proof(&fixtures::case_demo_a(), fixtures::tampered_demo_a_red_round(), fixtures::trace_t_demo_a(), fixtures::trace_la_demo_a());
}

#[test, expected_failure]
fun reject_demo_a_adv_eval() {
    test_util::check_verify_proof(&fixtures::case_demo_a(), fixtures::tampered_demo_a_adv_eval(), fixtures::trace_t_demo_a(), fixtures::trace_la_demo_a());
}

#[test, expected_failure]
fun reject_demo_a_chart_eval() {
    test_util::check_verify_proof(&fixtures::case_demo_a(), fixtures::tampered_demo_a_chart_eval(), fixtures::trace_t_demo_a(), fixtures::trace_la_demo_a());
}

#[test, expected_failure]
fun reject_demo_a_zm_q0() {
    test_util::check_verify_proof(&fixtures::case_demo_a(), fixtures::tampered_demo_a_zm_q0(), fixtures::trace_t_demo_a(), fixtures::trace_la_demo_a());
}

#[test, expected_failure]
fun reject_demo_a_zm_qhat() {
    test_util::check_verify_proof(&fixtures::case_demo_a(), fixtures::tampered_demo_a_zm_qhat(), fixtures::trace_t_demo_a(), fixtures::trace_la_demo_a());
}

#[test, expected_failure]
fun reject_demo_a_zm_qhat_shift() {
    test_util::check_verify_proof(&fixtures::case_demo_a(), fixtures::tampered_demo_a_zm_qhat_shift(), fixtures::trace_t_demo_a(), fixtures::trace_la_demo_a());
}

#[test, expected_failure]
fun reject_demo_a_zm_pi() {
    test_util::check_verify_proof(&fixtures::case_demo_a(), fixtures::tampered_demo_a_zm_pi(), fixtures::trace_t_demo_a(), fixtures::trace_la_demo_a());
}

#[test, expected_failure]
fun reject_demo_a_truncated() {
    test_util::check_verify_proof(&fixtures::case_demo_a(), fixtures::tampered_demo_a_truncated(), fixtures::trace_t_demo_a(), fixtures::trace_la_demo_a());
}

#[test, expected_failure]
fun reject_demo_a_extended() {
    test_util::check_verify_proof(&fixtures::case_demo_a(), fixtures::tampered_demo_a_extended(), fixtures::trace_t_demo_a(), fixtures::trace_la_demo_a());
}

#[test, expected_failure]
fun reject_demo_a_noncanonical() {
    test_util::check_verify_proof(&fixtures::case_demo_a(), fixtures::tampered_demo_a_noncanonical(), fixtures::trace_t_demo_a(), fixtures::trace_la_demo_a());
}

#[test]
fun verify_demo_b() {
    test_util::check_verify(&fixtures::case_demo_b(), vector[], vector[]);
}

#[test]
fun submit_demo_b() {
    test_util::check_submit(&fixtures::case_demo_b(), fixtures::chart_bytes_demo(), fixtures::chart_proof_demo(), vector[], vector[], vector[]);
}

#[test, expected_failure]
fun reject_demo_b_adv_commitment() {
    test_util::check_verify_proof(&fixtures::case_demo_b(), fixtures::tampered_demo_b_adv_commitment(), vector[], vector[]);
}

#[test, expected_failure]
fun reject_demo_b_gkr_layer1() {
    test_util::check_verify_proof(&fixtures::case_demo_b(), fixtures::tampered_demo_b_gkr_layer1(), vector[], vector[]);
}

#[test, expected_failure]
fun reject_demo_b_gkr_round() {
    test_util::check_verify_proof(&fixtures::case_demo_b(), fixtures::tampered_demo_b_gkr_round(), vector[], vector[]);
}

#[test, expected_failure]
fun reject_demo_b_gkr_children() {
    test_util::check_verify_proof(&fixtures::case_demo_b(), fixtures::tampered_demo_b_gkr_children(), vector[], vector[]);
}

#[test, expected_failure]
fun reject_demo_b_row_round() {
    test_util::check_verify_proof(&fixtures::case_demo_b(), fixtures::tampered_demo_b_row_round(), vector[], vector[]);
}

#[test, expected_failure]
fun reject_demo_b_claim_first() {
    test_util::check_verify_proof(&fixtures::case_demo_b(), fixtures::tampered_demo_b_claim_first(), vector[], vector[]);
}

#[test, expected_failure]
fun reject_demo_b_claim_last() {
    test_util::check_verify_proof(&fixtures::case_demo_b(), fixtures::tampered_demo_b_claim_last(), vector[], vector[]);
}

#[test, expected_failure]
fun reject_demo_b_red_round() {
    test_util::check_verify_proof(&fixtures::case_demo_b(), fixtures::tampered_demo_b_red_round(), vector[], vector[]);
}

#[test, expected_failure]
fun reject_demo_b_adv_eval() {
    test_util::check_verify_proof(&fixtures::case_demo_b(), fixtures::tampered_demo_b_adv_eval(), vector[], vector[]);
}

#[test, expected_failure]
fun reject_demo_b_chart_eval() {
    test_util::check_verify_proof(&fixtures::case_demo_b(), fixtures::tampered_demo_b_chart_eval(), vector[], vector[]);
}

#[test, expected_failure]
fun reject_demo_b_trace_eval() {
    test_util::check_verify_proof(&fixtures::case_demo_b(), fixtures::tampered_demo_b_trace_eval(), vector[], vector[]);
}

#[test, expected_failure]
fun reject_demo_b_zm_q0() {
    test_util::check_verify_proof(&fixtures::case_demo_b(), fixtures::tampered_demo_b_zm_q0(), vector[], vector[]);
}

#[test, expected_failure]
fun reject_demo_b_zm_qhat() {
    test_util::check_verify_proof(&fixtures::case_demo_b(), fixtures::tampered_demo_b_zm_qhat(), vector[], vector[]);
}

#[test, expected_failure]
fun reject_demo_b_zm_qhat_shift() {
    test_util::check_verify_proof(&fixtures::case_demo_b(), fixtures::tampered_demo_b_zm_qhat_shift(), vector[], vector[]);
}

#[test, expected_failure]
fun reject_demo_b_zm_pi() {
    test_util::check_verify_proof(&fixtures::case_demo_b(), fixtures::tampered_demo_b_zm_pi(), vector[], vector[]);
}

#[test, expected_failure]
fun reject_demo_b_truncated() {
    test_util::check_verify_proof(&fixtures::case_demo_b(), fixtures::tampered_demo_b_truncated(), vector[], vector[]);
}

#[test, expected_failure]
fun reject_demo_b_extended() {
    test_util::check_verify_proof(&fixtures::case_demo_b(), fixtures::tampered_demo_b_extended(), vector[], vector[]);
}

#[test, expected_failure]
fun reject_demo_b_noncanonical() {
    test_util::check_verify_proof(&fixtures::case_demo_b(), fixtures::tampered_demo_b_noncanonical(), vector[], vector[]);
}

#[test]
fun chart_perfect() {
    test_util::check_chart(&fixtures::case_perfect_a(), fixtures::chart_bytes_perfect(), fixtures::chart_proof_perfect());
}

#[test]
fun verify_perfect_a() {
    test_util::check_verify(&fixtures::case_perfect_a(), fixtures::trace_t_perfect_a(), fixtures::trace_la_perfect_a());
}

#[test]
fun submit_perfect_a() {
    test_util::check_submit(&fixtures::case_perfect_a(), fixtures::chart_bytes_perfect(), fixtures::chart_proof_perfect(), fixtures::events_perfect_a(), fixtures::trace_t_perfect_a(), fixtures::trace_la_perfect_a());
}

#[test]
fun upload_perfect_a() {
    test_util::check_upload(&fixtures::case_perfect_a(), fixtures::events_perfect_a());
}

#[test]
fun verify_perfect_b() {
    test_util::check_verify(&fixtures::case_perfect_b(), vector[], vector[]);
}

#[test]
fun submit_perfect_b() {
    test_util::check_submit(&fixtures::case_perfect_b(), fixtures::chart_bytes_perfect(), fixtures::chart_proof_perfect(), vector[], vector[], vector[]);
}

#[test]
fun chart_random0() {
    test_util::check_chart(&fixtures::case_random0_a(), fixtures::chart_bytes_random0(), fixtures::chart_proof_random0());
}

#[test]
fun verify_random0_a() {
    test_util::check_verify(&fixtures::case_random0_a(), fixtures::trace_t_random0_a(), fixtures::trace_la_random0_a());
}

#[test]
fun submit_random0_a() {
    test_util::check_submit(&fixtures::case_random0_a(), fixtures::chart_bytes_random0(), fixtures::chart_proof_random0(), fixtures::events_random0_a(), fixtures::trace_t_random0_a(), fixtures::trace_la_random0_a());
}

#[test]
fun upload_random0_a() {
    test_util::check_upload(&fixtures::case_random0_a(), fixtures::events_random0_a());
}

#[test]
fun chart_random1() {
    test_util::check_chart(&fixtures::case_random1_b(), fixtures::chart_bytes_random1(), fixtures::chart_proof_random1());
}

#[test]
fun verify_random1_b() {
    test_util::check_verify(&fixtures::case_random1_b(), vector[], vector[]);
}

#[test]
fun submit_random1_b() {
    test_util::check_submit(&fixtures::case_random1_b(), fixtures::chart_bytes_random1(), fixtures::chart_proof_random1(), vector[], vector[], vector[]);
}

#[test]
fun chart_bench500() {
    test_util::check_chart(&fixtures::case_bench500_a(), fixtures::chart_bytes_bench500(), fixtures::chart_proof_bench500());
}

#[test]
fun verify_bench500_a() {
    test_util::check_verify(&fixtures::case_bench500_a(), fixtures::trace_t_bench500_a(), fixtures::trace_la_bench500_a());
}

#[test]
fun submit_bench500_a() {
    test_util::check_submit(&fixtures::case_bench500_a(), vector[], vector[], vector[], fixtures::trace_t_bench500_a(), fixtures::trace_la_bench500_a());
}

#[test]
fun upload_bench500_a() {
    test_util::check_upload(&fixtures::case_bench500_a(), fixtures::events_bench500_a());
}

#[test]
fun verify_bench500_b() {
    test_util::check_verify(&fixtures::case_bench500_b(), vector[], vector[]);
}

#[test]
fun submit_bench500_b() {
    test_util::check_submit(&fixtures::case_bench500_b(), vector[], vector[], vector[], vector[], vector[]);
}

#[test]
fun chart_bench3000() {
    test_util::check_chart(&fixtures::case_bench3000_a(), fixtures::chart_bytes_bench3000(), fixtures::chart_proof_bench3000());
}

#[test]
fun verify_bench3000_a() {
    test_util::check_verify(&fixtures::case_bench3000_a(), fixtures::trace_t_bench3000_a(), fixtures::trace_la_bench3000_a());
}

#[test]
fun submit_bench3000_a() {
    test_util::check_submit(&fixtures::case_bench3000_a(), vector[], vector[], vector[], fixtures::trace_t_bench3000_a(), fixtures::trace_la_bench3000_a());
}

#[test]
fun upload_bench3000_a() {
    test_util::check_upload(&fixtures::case_bench3000_a(), fixtures::events_bench3000_a());
}

#[test]
fun verify_bench3000_b() {
    test_util::check_verify(&fixtures::case_bench3000_b(), vector[], vector[]);
}

#[test]
fun submit_bench3000_b() {
    test_util::check_submit(&fixtures::case_bench3000_b(), vector[], vector[], vector[], vector[], vector[]);
}
