import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {privateKeyToAccount} from 'viem/accounts';import {toHex,encodeAbiParameters} from 'viem';
import {parseOsu,replayEvents,canonicalChartHash} from '../chart.mjs';import {rustHeader,traceRoot,sessionDigest,validateSeal,eventBytes} from '../proof.mjs';
const osu=Buffer.from('osu file format v14\n[General]\nMode:3\n[Difficulty]\nCircleSize:4\n[HitObjects]\n64,192,500,1,0,0:0:0:0:\n192,192,1500,128,0,2000:0:0:0:0:\n');const chart=parseOsu(osu);
const base={version:2,mods:{bits:0,rate:1,hpOverride:null},inputs:[[0,1000,true],[0,1001,false]]};
test('exact source bytes identity and canonical chart timing',()=>{assert.notEqual(chart.webBeatmapHash,parseOsu(Buffer.concat([Buffer.from([239,187,191]),osu])).webBeatmapHash);assert.equal(chart.firstNoteMs,500);assert.deepEqual(chart.chart.notes[1],{lane:1,start_us:1500000,end_us:2000000});assert.equal(replayEvents({replay:base,timing:{chartDelayMs:500}},chart)[0].timestamp_us,500000);});
test('rejects mods, forged timing and repeated keydown',()=>{assert.throws(()=>replayEvents({replay:base,timing:{chartDelayMs:0}},chart));assert.throws(()=>replayEvents({replay:{...base,mods:{bits:1,rate:1}},timing:{chartDelayMs:500}},chart));assert.throws(()=>replayEvents({replay:{...base,inputs:[[0,1000,true],[0,1001,true]]},timing:{chartDelayMs:500}},chart));assert.throws(()=>parseOsu(Buffer.from(osu.toString().replace('CircleSize:4','CircleSize:7'))));});
test('real signed hardware seal binds challenge and trace',async()=>{const device=privateKeyToAccount(toHex(77n,{size:32}));const word=toHex(1n,{size:32});const h={chainId:11155111n,verifier:device.address,matchId:word,sessionId:word,challenge:word,player:device.address,device:device.address,chartHash:word,rulesetId:word,bitstreamHash:word,inputPolicyHash:word};const events=replayEvents({replay:base,timing:{chartDelayMs:500}},chart);const root=traceRoot(h.sessionId,events);const input={header:rustHeader(h),events,footer:{event_count:events.length,duration_us:3000000,trace_root:[...Buffer.from(root.slice(2),'hex')]}};const digest=sessionDigest(h,events.length,3000000,root);const signature=await device.sign({hash:digest});assert.equal(await validateSeal(h,input,signature),digest);await assert.rejects(()=>validateSeal({...h,challenge:toHex(2n,{size:32})},input,signature));input.events[0].timestamp_us++;await assert.rejects(()=>validateSeal(h,input,signature));});

test("canonical chart hash matches Rust fixture",()=>{const fixture=JSON.parse(fs.readFileSync(new URL("../../../scoring/fixtures/demo.json",import.meta.url)));assert.equal(canonicalChartHash(fixture.chart),toHex(Uint8Array.from(fixture.header.chart_hash)));});

test('no-input gameplay encodes empty trace as ABI bytes for a valid zero score',()=>{const events=replayEvents({replay:{...base,inputs:[]},timing:{chartDelayMs:500}},chart);assert.deepEqual(events,[]);assert.equal(eventBytes(events),'0x');assert.doesNotThrow(()=>encodeAbiParameters([{type:'bytes'}],[eventBytes(events)]));});
